version: '3.8'

services:
  backend:
    build: 
      context: ./backend
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - PORT=8080
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USERNAME=rxai_user
      - DB_PASSWORD=rxai_password
      - DB_DATABASE=rxai
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=${OPENAI_MODEL}
      - DROPBOX_ACCESS_TOKEN=${DROPBOX_ACCESS_TOKEN}
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm run start:dev

  ui:
    build:
      context: ./ui
    ports:
      - "3000:3000"
    volumes:
      - ./ui:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:8080
    command: npm start

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=rxai
      - MYSQL_USER=rxai_user
      - MYSQL_PASSWORD=rxai_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
    driver: local 