version: '3.8'

services:
  rxai:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=production
      - PORT=8000
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USERNAME=rxai_user
      - DB_PASSWORD=rxai_password
      - DB_DATABASE=rxai
      - DROPBOX_ACCESS_TOKEN=${DROPBOX_ACCESS_TOKEN}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=${OPENAI_MODEL}
      - GOOGLE_APPLICATION_CREDENTIALS=/app/rxai-450010-dcef583435c8.json
    restart: unless-stopped
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=rxai
      - MYSQL_USER=rxai_user
      - MYSQL_PASSWORD=rxai_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data:
    driver: local 