version: '3.8'

services:
  rxai:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./db.sqlite:/app/db.sqlite
      - sqlite_data:/app/data
    environment:
      - NODE_ENV=production
      - PORT=8000
    restart: unless-stopped

volumes:
  sqlite_data: 